@baseUrl=http://localhost:3000/api/v1/auth
@email=example@example.com
@password=password

###

# Signup
POST {{baseUrl}}/signup
content-type: application/json

{
  "name":"akasuo",
  "email":"{{email}}",
  "password":"{{password}}"
}

###

# Login
POST {{baseUrl}}/login
content-type: application/json

{
  "email":"{{email}}",
  "password":"{{password}}"
}