@baseUrl=http://localhost:3000/api/v1/vote
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNranVoZHltajAwMDIzY3Y5dXBubnVxemEiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNjEwNDg1MzM2LCJleHAiOjE2MTEwOTAxMzZ9.1BuD78sorKsg032kP1W9d9wPR6N077B0UUUFYvPv49k
@vote-id=ckjtv20mi0000rsv9ahqf5qhv

###

# 投票一覧の取得
GET {{baseUrl}}/

###

# 投票の作成
POST {{baseUrl}}/
content-type: application/json
Authorization: {{token}}

{
  "title":"最強のエディタ",
  "imagePath":"https://i.gzn.jp/img/2018/01/15/google-gorilla-ban/00.jpg",
  "endDateTime":"1610683200000",
  "leftImageTitle":"Vim",
  "rightImageTitle":"Emacs"
}

###
# ID指定した投票を取得
GET {{baseUrl}}/ckjum4plt000080v982lpdtvu

###
#投票に参加
POST {{baseUrl}}/ckjum4plt000080v982lpdtvu
content-type: application/json
Authorization: {{token}}

{
  "destination":"left"
}

###

GET {{baseUrl}}/search/title/最強

###
GET {{baseUrl}}/search/tag/ほげ